# Задание 1

In [ ]:
import numpy as np

In [ ]:
n=int(input('Введите количество элементов: n='))

Введите количество элементов: n=10


In [ ]:
a=np.arange(0,n)

In [ ]:
res_a=np.flip(a)

In [ ]:
res_a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2

In [ ]:
matrix=np.diag(res_a)

In [ ]:
matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
summ_matrix=np.trace(matrix)

In [ ]:
summ_matrix

45

# Задание 3

In [ ]:
from numpy import linalg

In [ ]:
a=np.array([[4,2,1],[1,3,0],[0,5,4]])
b=np.array([4,12,-3])
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

# Задание 4

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)

In [ ]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [ ]:
cosine=np.dot(users_stats, next_user_stats)/(np.linalg.norm(users_stats, axis=1))/np.linalg.norm(next_user_stats)


In [ ]:
print(cosine)

[0.2        0.84515425 0.4        0.79056942 0.4        0.
 0.         0.9486833  0.         0.        ]


In [ ]:
best_user_=np.argmax(cosine)
print('самый похожий пользователь:', users_stats[best_user_, :])

самый похожий пользователь: [0 1 1 0 0 0]
